---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sedgwickenv

<!-- badges: start -->
<!-- badges: end -->

Load environmental data for 24 vegetation sampling plots at University of California Sedgwick Reserve in Santa Barbara CA, USA. Data were collected by Nathan Kraft, Gaurav Kandlikar, Andrew Kleinhesselink and the Kraft Lab.     


## Installation

You can install this package from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("akleinhesselink/sedgwickenv")
```

## Usage

`library(sedgwickenv)` will load the following datasets:

* __sedgwick_env__: dataframe with average environmental conditions at all 24 sites 
* __sedgwick_ibutton__: daily Tmax, Tmin and Tavg spring temperatures at 24 sites 
* __sedgwick_soil_moisture__: spring soil moisture recorded at each of the 24 sites 
* __sedgwick_boundary__: SpatialPolygon file showing boundaries of Sedgwick for maps 
* __sedgwick_DEM__: raster showing elevation across Sedgwick at roughly 10 m resolution 
* __sedgwick_soil_depth__: soil depth recorded at each plot at each site 


